# Generated by Django 3.1.2 on 2020-10-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tertimonial",
            new_name="Testimonial",
        ),
    ]
